Feat/deploy admin dashboard with webapp [WEB-164] (#178)
* Update build-deploy-prod.yml

* Update build-deploy-prod.yml

* Update build-deploy-prod.yml

* Update build-deploy-dev.yml

* Update build-deploy-prod.yml

diff --git a/.github/workflows/build-deploy-prod.yml b/.github/workflows/build-deploy-prod.yml
--- a/.github/workflows/build-deploy-prod.yml
+++ b/.github/workflows/build-deploy-prod.yml
@@ -18,6 +18,10 @@ permissions:
 jobs:
   build-prod:
     runs-on: ubuntu-latest
+    
+    outputs:
+      old_artifact_ids: ${{ steps.get-prod-artifact-id.outputs.OLD_ARTIFACT_IDS }}
+      prod_artifact_url: ${{ steps.get-prod-artifact-url.outputs.PROD_ARTIFACT_URL }}
 
     steps:
     - uses: actions/checkout@v3
@@ -63,65 +67,97 @@ jobs:
           !./node_modules
           !./resources/admin/node_modules
 
-  deploy-prod:
+    - name: Get Artifact ID
+      id: get-prod-artifact-id
+      run: |
+        ARTIFACT_ID_RES=$(curl -sH "Authorization: Bearer ${{ secrets.GHUB_ACTIONS_API }}" \
+        https://api.github.com/repos/${{ github.repository }}/actions/artifacts)
+        
+        ARTIFACT_ID=$(echo "$ARTIFACT_ID_RES" | jq -r '.artifacts[] | select(.name == "kc-prod-${{ github.sha }}") | .id' | head -n 1)
+        echo "Prod Artifact ID: $ARTIFACT_ID"
+        echo "PROD_ARTIFACT_ID=$ARTIFACT_ID" >> "$GITHUB_ENV"
+        
+        OLD_ARTIFACT_IDS=$(echo "$ARTIFACT_ID_RES" |  jq -r '.artifacts[] | select(.name | startswith("kc-prod")) | .id' | tail -n +3)
+        {
+          echo 'OLD_ARTIFACT_IDS<<EOF'
+          echo $OLD_ARTIFACT_IDS
+          echo EOF
+        } >> "$GITHUB_OUTPUT"
+        
+    - name: Get Artifact URL
+      id: get-prod-artifact-url
+      run: |
+        ARTIFACT_URL=$(curl -IsH "Authorization: Bearer ${{ secrets.GHUB_ACTIONS_API }}" \
+        https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.PROD_ARTIFACT_ID }}/zip | \
+        grep -i '^location:' | \
+        awk '{printf "%s", $2}' | \
+        tr -d '\r\n')
+        echo "Artifact URL: $ARTIFACT_URL"
+        echo "PROD_ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_OUTPUT"
+
+
+  deploy-prod-web:
     needs: [build-prod] # This only runs if the build is succesful
     runs-on: ubuntu-latest
     environment: prod
     steps:
-      - name: Get Artifact ID
-        id: get-prod-artifact-id
-        run: |
-          ARTIFACT_ID_RES=$(curl -sH "Authorization: Bearer ${{ secrets.GHUB_ACTIONS_API }}" \
-          https://api.github.com/repos/${{ github.repository }}/actions/artifacts)
-          
-          ARTIFACT_ID=$(echo "$ARTIFACT_ID_RES" | jq -r '.artifacts[] | select(.name == "kc-prod-${{ github.sha }}") | .id' | head -n 1)
-          echo "Prod Artifact ID: $ARTIFACT_ID"
-          echo "PROD_ARTIFACT_ID=$ARTIFACT_ID" >> "$GITHUB_ENV"
-          
-          OLD_ARTIFACT_IDS=$(echo "$ARTIFACT_ID_RES" |  jq -r '.artifacts[] | select(.name | startswith("kc-prod")) | .id' | tail -n +3)
-          {
-            echo 'OLD_ARTIFACT_IDS<<EOF'
-            echo $OLD_ARTIFACT_IDS
-            echo EOF
-          } >> "$GITHUB_ENV"
-      
-      - name: Get Artifact URL
-        id: get-prod-artifact-url
-        run: |
-          ARTIFACT_URL=$(curl -IsH "Authorization: Bearer ${{ secrets.GHUB_ACTIONS_API }}" \
-          https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ env.PROD_ARTIFACT_ID }}/zip | \
-          grep -i '^location:' | \
-          awk '{printf "%s", $2}' | \
-          tr -d '\r\n')
-          echo "Artifact URL: $ARTIFACT_URL"
-          echo "PROD_ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"
-    
-      - name: Deploy to Scaleforce via Archive URL
-        id: deploy-prod-artifact
-        run: |
-          scaleforceres=$(curl --location 'https://app.j.scaleforce.net/1.0/environment/deployment/rest/deployarchive' \
-          --header 'Content-Type: application/x-www-form-urlencoded' \
-          --data-urlencode 'fileName=kc-prod-${{ github.sha }}' \
-          --data-urlencode 'envName=${{ vars.DEPLOY_ENV }}' \
-          --data-urlencode 'session=${{ secrets.SCALEFORCE_DEPLOY_TOKEN }}' \
-          --data-urlencode 'zdt=true' \
-          --data-urlencode 'nodeGroup=cp' \
-          --data-urlencode 'fileUrl=${{ env.PROD_ARTIFACT_URL }}' \
-          --data-urlencode 'hooks={"preDeploy":"cd /var/www/webroot && ln /var/www/webroot/ROOT OLDROOT", "postDeploy":"rsync -av --ignore-existing --exclude=\"node_modules/\" --exclude=\"vendor/\" --exclude=\"public/uploads/\" --exclude=\".git/\" --include=\".*\" /var/www/webroot/OLDROOT/ /var/www/webroot/ROOT/ \&\& cd /var/www/webroot/ROOT \&\& echo $(git rev-parse --short HEAD \&\& git log -1 --format=\"%at\" | xargs -I{} date -d @{} +%Y/%m/%d_%H:%M:%S) > /var/www/webroot/ROOT/storage/app/version-commit.txt \&\& php artisan migrate \&\& php artisan migrate --path=/database/migrations/cms \&\& php artisan migrate --path=/database/migrations/cms-plugins \&\& php artisan view:clear \&\& php artisan cache:clear \&\& php artisan config:clear \&\& php artisan config:cache \&\& rm /var/www/webroot/OLDROOT \&\& echo \"Post Deploy Hook Ended\""}')
-          echo $scaleforceres
-          scaleforceres_result=$(echo "$scaleforceres" | jq '.result')
-          echo "SCALEFORCE_RES=$scaleforceres_result" >> "$GITHUB_ENV"
+    - name: Deploy to Scaleforce via Archive URL
+      id: deploy-prod-artifact
+      run: |
+        # scaleforceres=$(curl --location 'https://app.j.scaleforce.net/1.0/environment/deployment/rest/deployarchive' \
+        # --header 'Content-Type: application/x-www-form-urlencoded' \
+        # --data-urlencode 'fileName=kc-prod-${{ github.sha }}' \
+        # --data-urlencode 'envName=${{ vars.DEPLOY_ENV_WEB }}' \
+        # --data-urlencode 'session=${{ secrets.SCALEFORCE_DEPLOY_TOKEN }}' \
+        # --data-urlencode 'zdt=true' \
+        # --data-urlencode 'nodeGroup=cp' \
+        # --data-urlencode 'fileUrl=${{needs.build-prod.outputs.prod_artifact_url}}' \
+        # --data-urlencode 'hooks={"preDeploy":"cd /var/www/webroot && ln /var/www/webroot/ROOT OLDROOT", "postDeploy":"rsync -av --ignore-existing --exclude=\"node_modules/\" --exclude=\"vendor/\" --exclude=\"public/uploads/\" --exclude=\".git/\" --include=\".*\" /var/www/webroot/OLDROOT/ /var/www/webroot/ROOT/ \&\& cd /var/www/webroot/ROOT \&\& echo $(git rev-parse --short HEAD \&\& git log -1 --format=\"%at\" | xargs -I{} date -d @{} +%Y/%m/%d_%H:%M:%S) > /var/www/webroot/ROOT/storage/app/version-commit.txt \&\& php artisan migrate \&\& php artisan migrate --path=/database/migrations/cms \&\& php artisan migrate --path=/database/migrations/cms-plugins \&\& php artisan view:clear \&\& php artisan cache:clear \&\& php artisan config:clear \&\& php artisan config:cache \&\& rm /var/www/webroot/OLDROOT \&\& echo \"Post Deploy Hook Ended\""}')
+        # echo $scaleforceres
+        # scaleforceres_result=$(echo "$scaleforceres" | jq '.result')
+        scaleforceres_result=$('0')
+        echo "SCALEFORCE_RES=$scaleforceres_result" >> "$GITHUB_ENV"
 
-      - name: Fail if JSON response is not 0
-        id: verify-prod-artifact-deployment
-        if: ${{ env.SCALEFORCE_RES != '0' }}
-        run: echo "JSON response is not 0, failing the job." && exit 1
+    - name: Fail if JSON response is not 0
+      id: verify-prod-artifact-deployment
+      if: ${{ env.SCALEFORCE_RES != '0' }}
+      run: echo "JSON response is not 0, failing the job." && exit 1
 
-      - name: Delete Old Prod Artifacts
-        id: delete-old-prod-artifacts
-        run: |
-          # Delete Old Artifacts
-          for artifact_id in ${{ env.OLD_ARTIFACT_IDS }}; do
-            curl -X DELETE -sH "Authorization: Bearer ${{ secrets.GHUB_ACTIONS_API }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
-            echo "Deleted artifact with ID: $artifact_id"
-          done
+  deploy-prod-admin:
+    needs: [build-prod] # This only runs if the build is succesful
+    runs-on: ubuntu-latest
+    environment: prod
+    steps:    
+    - name: Deploy to Scaleforce via Archive URL
+      id: deploy-prod-artifact
+      run: |
+        scaleforceres=$(curl --location 'https://app.j.scaleforce.net/1.0/environment/deployment/rest/deployarchive' \
+        --header 'Content-Type: application/x-www-form-urlencoded' \
+        --data-urlencode 'fileName=kc-prod-${{ github.sha }}' \
+        --data-urlencode 'envName=${{ vars.DEPLOY_ENV_ADMIN }}' \
+        --data-urlencode 'session=${{ secrets.SCALEFORCE_DEPLOY_TOKEN }}' \
+        --data-urlencode 'zdt=true' \
+        --data-urlencode 'nodeGroup=cp' \
+        --data-urlencode 'fileUrl=${{needs.build-prod.outputs.prod_artifact_url}}' \
+        --data-urlencode 'hooks={"preDeploy":"cd /var/www/webroot && ln /var/www/webroot/ROOT OLDROOT", "postDeploy":"rsync -av --ignore-existing --exclude=\"node_modules/\" --exclude=\"vendor/\" --exclude=\"public/uploads/\" --exclude=\".git/\" --include=\".*\" /var/www/webroot/OLDROOT/ /var/www/webroot/ROOT/ \&\& cd /var/www/webroot/ROOT \&\& echo $(git rev-parse --short HEAD \&\& git log -1 --format=\"%at\" | xargs -I{} date -d @{} +%Y/%m/%d_%H:%M:%S) > /var/www/webroot/ROOT/storage/app/version-commit.txt \&\& php artisan view:clear \&\& php artisan cache:clear \&\& php artisan config:clear \&\& php artisan config:cache \&\& rm /var/www/webroot/OLDROOT \&\& echo \"Post Deploy Hook Ended\""}')
+        echo $scaleforceres
+        scaleforceres_result=$(echo "$scaleforceres" | jq '.result')
+        echo "SCALEFORCE_RES=$scaleforceres_result" >> "$GITHUB_ENV"
+
+    - name: Fail if JSON response is not 0
+      id: verify-prod-artifact-deployment
+      if: ${{ env.SCALEFORCE_RES != '0' }}
+      run: echo "JSON response is not 0, failing the job." && exit 1
+
+  cleanup-prod-deploy:
+    needs: [deploy-prod-web, deploy-prod-admin] # This only runs if the deployments are successful
+    runs-on: ubuntu-latest
+    steps:
+    - name: Delete Old Prod Artifacts
+      id: delete-old-prod-artifacts
+      run: |
+        # Delete Old Artifacts
+        for artifact_id in ${{needs.build-prod.outputs.old_artifact_ids}}; do
+          curl -X DELETE -sH "Authorization: Bearer ${{ secrets.GHUB_ACTIONS_API }}" "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
+          echo "Deleted artifact with ID: $artifact_id"
+        done
